services:
  # 1. Reverse Proxy (Gateway)
  proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - frontend-net
    depends_on:
      - api

  # 2. Application Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/microservices_db
      - API_KEY=microstack-dev-secret-key-change-in-prod
    networks:
      - frontend-net
      - backend-net
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - pdf_storage:/app/generated_pdfs
      

  # 3. Asynchronous Task Worker (Celery)
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks.celery_app worker --loglevel=info
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/microservices_db
    networks:
      - backend-net
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - pdf_storage:/app/generated_pdfs

  # 4. Cache Storage & Message Broker
  cache:
    image: redis:7-alpine
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 5. PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=microservices_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d microservices_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 6. Metrics Scraper (Prometheus)
  prometheus:
    image: prom/prometheus:v2.50.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - frontend-net
      - backend-net

  # 7. Visualization Dashboard (Grafana)
  grafana:
    image: grafana/grafana:10.3.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - frontend-net
      - backend-net
    depends_on:
      - prometheus

# Persistent Data Volumes & Networks
volumes:
  postgres_data:
  pdf_storage:

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge