apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2 # Scaled to 2 worker instances
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: docker-microstack-app:latest
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "tasks.celery_app", "worker", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: microstack-config
            - secretRef:
                name: microstack-secrets
          volumeMounts:
            - name: pdf-storage
              mountPath: /app/generated_pdfs
      volumes:
        - name: pdf-storage
          persistentVolumeClaim:
            claimName: pdf-storage-pvc